server:
  port: 9002 #端口
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启Spring Cloud的重试功能
  application:
    name: service-order #服务名称
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ ,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册

# 在feign中开启hystrix熔断
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 500 //线程超时,调用Fallback方法
    circuitBreaker:
      requestVolumeThreshold: 3  //10秒内出现3个以上请求(已临近阀值),并且出错率在50%以上,开启断路器.断开服务,调用Fallback方法

#logging:
#  level:
#    root: debug

#修改ribbon的负载均衡策略   服务名 -  ribbon - NFLoadBalancerRuleClassName : 策略
#service-product:
#  ribbon:
#    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    ConnectTimeout: 250 # Ribbon的连接超时时间
#    ReadTimeout: 1000 # Ribbon的数据读取超时时间
#    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
#    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
#    MaxAutoRetries: 1 # 对当前实例的重试次数

